### ISSUE TITLE
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

### ISSUE THREAD

**Issue by mounirlahsini** [OCA/odoorpc#38]
Hello i recently installed odoorpc trying to migrate data from odoo v8 to odoo v11 and while trying to connect to the host where odoo 8 is installed i get this error this is the pyhton code

import odoorpc
odoo = odoorpc.ODOO('localhost' port=80)
-- tried this too odoo = odoorpc.ODOO('localhost')
print(odoo.db.list())

and this is the full error i get
Traceback (most recent call last):
File "/home/mounirlahsini/Downloads/odooV11migration/AccountingScript/ApiMigration.py", line 5, in 
odoo = odoorpc.ODOO('ubuntudoo.daphne-solutions.com')
File "/home/mounirlahsini/.local/lib/python2.7/site-packages/odoorpc/odoo.py", line 105, in init
self._host, self._port, timeout, version, opener=opener)
File "/home/mounirlahsini/.local/lib/python2.7/site-packages/odoorpc/rpc/init.py", line 209, in init
self._proxy_json, self._proxy_http = self._get_proxies()
File "/home/mounirlahsini/.local/lib/python2.7/site-packages/odoorpc/rpc/init.py", line 224, in _get_proxies
result = proxy_json('/web/webclient/version_info')['result']
File "/home/mounirlahsini/.local/lib/python2.7/site-packages/odoorpc/rpc/jsonrpclib.py", line 124, in call
response = self._opener.open(request, timeout=self._timeout)
File "/usr/lib/python2.7/urllib2.py", line 429, in open
response = self._open(req, data)
File "/usr/lib/python2.7/urllib2.py", line 447, in _open
'_open', req)
File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
return self.do_open(httplib.HTTPConnection, req)
File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

please help, and thank you.

**Comment by pedrobaeza** [comment]
Migrating from v8 to v11? Try OpenUpgrade for this, but for both it requires very technical skills.

For this, you should provide a valid URL and port. It seems port 80 is not the suitable one.
