### ISSUE TITLE
List or restore not possible after database dropped in Odoo v12.0

### ISSUE THREAD

**Issue by hhobein** [OCA/odoorpc#40]
This only happens on Odoo v12.0 - v11.0 works like a charm. :-)

To reproduce:
Drop your last db with .db.drop(..) - after that try to list with .db.list() or try to restore a backup with db.restore(..). 
An Http-Exception is thrown.

**Comment by pedrobaeza** [comment]
More details, please... Traceback at the other side (Odoo side). I think it's something of Odoo, not OdooRPC.

**Comment by hhobein** [comment]
`2019-02-04 17:42:29,369 6552 INFO None odoo.service.db: DROP DB: beladomo_flaschenshop_git 
2019-02-04 17:42:29,425 6552 INFO None odoo.sql_db: Connection to the database failed 
2019-02-04 17:42:29,429 6552 INFO beladomo_flaschenshop_git werkzeug: 10.0.4.12 - - [04/Feb/2019 17:42:29] "POST /jsonrpc HTTP/1.1" 500 - 
4 0.188 0.275
2019-02-04 17:42:29,437 6552 ERROR beladomo_flaschenshop_git werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/service/server.py", line 350, in app
    return self.app(e, s)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/http.py", line 1485, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/addons/http_routing/models/ir_http.py", line 394, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/addons/utm/models/ir_http.py", line 27, in _dispatch
    return cls._set_utm(response)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/addons/utm/models/ir_http.py", line 19, in _set_utm
    for var, dummy, cook in request.env['utm.mixin'].tracking_fields():
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/http.py", line 258, in env
    self._env = odoo.api.Environment(self.cr, self.uid, self.context)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/http.py", line 230, in cr
    self._cr = self.registry.cursor()
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/http.py", line 378, in registry
    return odoo.registry(self.db)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/__init__.py", line 81, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/modules/registry.py", line 74, in new
    registry.init(db_name)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/modules/registry.py", line 142, in init
    with closing(self.cursor()) as cr:
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/modules/registry.py", line 470, in cursor
    return self._db.cursor()
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/sql_db.py", line 657, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/sql_db.py", line 171, in __init__
    self._cnx = pool.borrow(dsn)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/sql_db.py", line 540, in _locked
    return fun(self, *args, **kwargs)
  File "/opt/odoo/sites/beladomo_flaschenshop/odoo/odoo/sql_db.py", line 608, in borrow
    **connection_info)
  File "/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "beladomo_flaschenshop_git" does not exist - - -
2019-02-04 17:42:30,443 6552 INFO beladomo_flaschenshop_git odoo.sql_db: Connection to the database failed 
2019-02-04 17:42:30,443 6552 INFO beladomo_flaschenshop_git odoo.http: Generating nondb routing 
2019-02-04 17:42:30,463 6552 INFO beladomo_flaschenshop_git werkzeug: 10.0.4.12 - - [04/Feb/2019 17:42:30] "POST /jsonrpc HTTP/1.1" 404 - 0 0.000 0.029
2019-02-04 17:42:31,480 6552 INFO ? werkzeug: 10.0.4.12 - - [04/Feb/2019 17:42:31] "POST /jsonrpc HTTP/1.1" 404 - 1 0.002 0.010
`

**Comment by pedrobaeza** [comment]
You are removing the DB in which you are connected?

**Comment by hhobein** [comment]
Yes - which is ok with odoorpc and odoo v11.0. I'm automating dropping and restoring a new database via git hooks. Or is working by accident on odoo v11.0?

**Comment by pedrobaeza** [comment]
@sebalix can confirm, but I would say yes, as you shouldn't connect to the database for doing that.

**Comment by hhobein** [comment]
That would be a limitation the odoo webinterface for database administration doesn't have:
You can restore a database without having one installed.
That said this sounds not well thought through. Or am I missing something here?

**Comment by pedrobaeza** [comment]
IMO, odoorpc is not for managing DBs, but well, some of you use this. I don't have right now clear where the source problem is. Let's see the main contributor of this project.

**Comment by sebalix** [comment]
Some news on this:

```python
>>> import odoorpc
>>> odoo = odoorpc.ODOO()
>>> odoo.db.list()
[]
>>> odoo.db.create('admin', 'test_odoorpc_v12')
# Here I logged on the instance through the UI
>>> odoo.db.drop('admin', 'test_odoorpc_v12')
True
>>> odoo.db.list()
[]
```

But if I log on Odoo with OdooRPC:
```python
>>> odoo.db.create('admin', 'test_odoorpc_v12')
>>> odoo.login('test_odoorpc_v12', 'admin', 'admin')
>>> odoo.db.list()
['test_odoorpc_v12']
>>> odoo.db.drop('admin', 'test_odoorpc_v12')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/salix/dev/OCA/odoorpc/odoorpc/db.py", line 227, in drop
    'args': [password, db]})
  File "/home/salix/dev/OCA/odoorpc/odoorpc/odoo.py", line 281, in json
    data = self._connector.proxy_json(url, params)
  File "/home/salix/dev/OCA/odoorpc/odoorpc/rpc/jsonrpclib.py", line 124, in __call__
    response = self._opener.open(request, timeout=self._timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
>>> odoo.db.list()
[]
```
Despite the error message the database is deleted, so there is a high chance that the error happens only in OdooRPC.

**Comment by sebalix** [comment]
@hhobein fix merged in `master`, closing
