### ISSUE TITLE
Does not work in odoo13

### ISSUE THREAD

**Issue by grey27** [OCA/odoorpc#54]
code:
```
import odoorpc

odoo = odoorpc.ODOO()
odoo.login('test_db')
```

logs:
```
Traceback (most recent call last):
  File "D:\PyCharm 2019.3.3\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm 2019.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/odoo13/my_addons/test_model/models/odoorpc_t.py", line 5, in <module>
    cli = odoo.login('test_db')
  File "C:\Users\grey27\AppData\Local\Programs\Python\Python37\lib\site-packages\odoorpc\odoo.py", line 355, in login
    {'db': db, 'login': login, 'password': password})
  File "C:\Users\grey27\AppData\Local\Programs\Python\Python37\lib\site-packages\odoorpc\odoo.py", line 285, in json
    data['error'])
odoorpc.error.RPCError: request not bound to a database

```

**Comment by altanmur** [comment]
Hello, Grey27

It is Working on me
<img width="449" alt="Screen Shot 2020-07-31 at 12 01 50" src="https://user-images.githubusercontent.com/31090100/88998921-b3ae0b80-d325-11ea-9b7d-962449d2aad3.png">

**Comment by pedrobaeza** [comment]
The login command of the issuer seems not correct. Anyway, as said, it's working in a general way, so closing unless there's an specific case presented here to be fixed.

**Comment by grey27** [comment]
![image](https://user-images.githubusercontent.com/39294698/89017382-d0116e80-d34c-11ea-84f2-a023e307c62f.png)
One database can and one database can't

**Comment by pedrobaeza** [comment]
Credentials may be not correct.
